apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.reservation.replicaCount }}
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - name: reservation-service
          image: "{{ .Values.reservation.image.repository }}:{{ .Values.reservation.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.reservation.containerPort }}
          env:
            {{- range $k, $v := .Values.reservation.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: reservation-service
  ports:
    - name: http
      port: {{ .Values.reservation.servicePort }}
      targetPort: {{ .Values.reservation.containerPort }}
  type: ClusterIP
