apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: search-service
spec:
  replicas: {{ .Values.search.replicaCount }}
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: "{{ .Values.search.image.repository }}:{{ .Values.search.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.search.containerPort }}
          env:
            {{- range $k, $v := .Values.search.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}

            - name: Mongo__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.name }}
                  key: MONGO_CONN_SEARCH

            - name: RabbitMq__User
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.name }}
                  key: RABBITMQ_USER
            - name: RabbitMq__Pass
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.name }}
                  key: RABBITMQ_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
    - name: http
      port: {{ .Values.search.servicePort }}
      targetPort: {{ .Values.search.containerPort }}
  type: ClusterIP