apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.search.replicaCount }}
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: "{{ .Values.search.image.repository }}:{{ .Values.search.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.search.containerPort }}
          env:
            {{- range $k, $v := .Values.search.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: search-service
  ports:
    - port: {{ .Values.search.servicePort }}
      targetPort: {{ .Values.search.containerPort }}
  type: ClusterIP
