{{- if not .Values.keyVault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SA_PASSWORD: {{ .Values.secrets.sqlserver.saPassword | quote }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-sql
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.sqlserver.replicaCount }}
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: devops-sql
  template:
    metadata:
      labels:
        app: devops-sql
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: sqlserver
          image: "{{ .Values.sqlserver.image.repository }}:{{ .Values.sqlserver.image.tag }}"
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: SA_PASSWORD
          volumeMounts:
            {{- if .Values.keyVault.enabled }}
            - name: key-vault
              mountPath: /mnt/key-vault
              readOnly: true
            {{- end }}
            - name: mssqldata
              mountPath: /var/opt/mssql
      volumes:
        {{- if .Values.keyVault.enabled }}
        - name: key-vault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Release.Name }}-key-vault
        {{- end }}
        - name: mssqldata
          persistentVolumeClaim:
            claimName: sqlserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: devops-sql
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: devops-sql
  ports:
    - name: sql
      port: {{ .Values.sqlserver.servicePort }}
      targetPort: 1433
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.sqlserver.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sqlserver.persistence.size | quote }}
